env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style:
    - warn
    - unix
  semi:
    - warn
    - always
  block-scoped-var: warn
  camelcase:
    - warn
    - properties: always
      ignoreImports: true
  curly: warn
  default-case: warn
  default-case-last: warn
  default-param-last: warn
  eqeqeq: warn
  grouped-accessor-pairs: warn
  no-case-declarations: warn
  no-empty: warn
  no-var: warn
  prefer-const: warn
  prefer-template: warn
  radix: warn
  spaced-comment: warn
  vars-on-top: warn

  '@typescript-eslint/no-empty-function': warn
  '@typescript-eslint/no-inferrable-types': warn
